[phases.setup]
nixPkgs = ["python3", "ffmpeg", "imagemagick"]

[phases.build]
cmds = ["chmod +x post_install.sh && ./post_install.sh", "pip install -r requirements.txt"]

[start]
cmd = "python main.py"
